const tintColorLight = '#333'
const tintColorDark = '#fff'

export default {
  green: '#00C781',
  red: '#FF4040',
  white: 'white',
  gray3: '#333',
  gray: '#666',
  gray9: '#999',
  link: '#008cd5',
  black: 'black',
  purple: '#3D138D',
  yellow: '#FFCA58',
  neutral4: '#A2423D',
  oct: '#0845A5',
  sun: '#f74e73',
  e3: '#e3e3e3',
  main: '#f74f73',
  chain: {
    NEAR: '#333',
    OCT: '#0845A5',
  },
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    screenBackground: '#eee',
    link: '#008cd5',
    cardBackground: '#fff',
    bannerBackground: '#e3e3e3',
    modalBackground: '#f6eee3',
    borderColor: '#e3e3e3',
    iconButtonBg: '#FFCA58',
    inputBackground: '#e3e3e3',
    tabBarBg: '#e3e3e3',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    screenBackground: '#000',
    link: '#FFCA58',
    cardBackground: '#222',
    bannerBackground: '#333',
    modalBackground: 'rgb(36,35,37)',
    borderColor: '#999',
    iconButtonBg: '#008cd5',
    inputBackground: '#222',
    tabBarBg: '#222',
  },
}
