import { NEAR_NETWORKS } from 'chain/near/constants'
import { OCT_NETWORKS } from 'chain/polkadot/constants'
import { AppChainType, Chain, NetworkType, Token, WalletSource } from 'types'
import icons from 'utils/icons'

export const CHAINS = [
  {
    icon: icons.NEAR_LOGO,
    chain: Chain.NEAR,
    defaultNetworks: NEAR_NETWORKS,
    sources: [WalletSource.MNEMONIC, WalletSource.PRIVATE_KEY],
    default: true,
  },
  {
    icon: icons.OCT_LOGO,
    chain: Chain.OCT,
    defaultNetworks: OCT_NETWORKS,
    sources: [WalletSource.MNEMONIC, WalletSource.PRIVATE_KEY],
  },
]

export const NATIVE_TOKENS: Token[] = [
  {
    name: 'NEAR',
    balance: '0',
    icon: icons.NEAR_LOGO,
    price: 0,
    symbol: 'NEAR',
    isNative: true,
    decimals: 24,
    chain: Chain.NEAR,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'Atocha',
    balance: '0',
    icon: icons.ATOCHA,
    price: 0,
    symbol: 'ATO',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.ATOCHA,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'DEIP',
    balance: '0',
    icon: icons.DEIP,
    price: 0,
    symbol: 'DEIP',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.DEIP,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'Myriad',
    balance: '0',
    icon: icons.MYRIAD,
    price: 0,
    symbol: 'MIRIA',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.MYRIAD,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'debionetwork',
    balance: '0',
    icon: icons.DEBIO,
    price: 0,
    symbol: 'DBIO',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.DEBIO,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'fusotao',
    balance: '0',
    icon: icons.FUSOTAO,
    price: 0,
    symbol: 'TAO',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.FUSOTAO,
    networkType: NetworkType.MAINNET,
  },
  {
    name: 'barnacle',
    balance: '0',
    icon: icons.BARNACLE,
    price: 0,
    symbol: 'BAR',
    isNative: true,
    decimals: 18,
    chain: Chain.OCT,
    appchainId: AppChainType.BARNACLE,
    networkType: NetworkType.MAINNET,
  },
]
